name: Deploy and Push Doxygen Documentation

on:
  repository_dispatch:
    types: [mmcesim-cli-push]

permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Run Doxygen
        run: chmod +x ./run && ./run
      - name: Commit Files
        run: |
          git config --local user.email "bot@mmcesim.org"
          git config --local user.name "mmcesim-bot"
          git add docs
          git commit -m"Update Doxygen Documentation" -m"Commit: https://github.com/mmcesim/mmcesim/commit/${{ github.event.client_payload.sha }}"
      - name: Push Changes
        uses: ad-m/github-push-action@master
